script: bundle exec rake test

bundler_args: --without tools

env:
  matrix:
    - >
      LIBSODIUM_MIRROR="http://download.dnscrypt.org/libsodium/releases/libsodium-%s.tar.gz"
      LIBSODIUM_VERSION=0.4.2
      LIBSODIUM_DIGEST=1a7901cdd127471724e854a8eb478247dc0ca67be549345c75fc6f2d4e05ed39

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
  - ree
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode

matrix:
  include:
    - rvm: 2.0.0
      env: >
        LIBSODIUM_MIRROR="https://github.com/jedisct1/libsodium/tarball/%s"
        LIBSODIUM_VERSION="master"

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: 2.0.0
      env: >
        LIBSODIUM_MIRROR="https://github.com/jedisct1/libsodium/tarball/%s"
        LIBSODIUM_VERSION="master"