script: bundle exec rake test

bundler_args: --without tools

env:
  - >
    LIBSODIUM_MIRROR="https://github.com/jedisct1/libsodium/tarball/%s"
    LIBSODIUM_VERSION="master"
# - >
#   LIBSODIUM_MIRROR="http://download.dnscrypt.org/libsodium/releases/libsodium-%s.tar.gz"
#   LIBSODIUM_VERSION=0.4.1
#   LIBSODIUM_DIGEST=65756c7832950401cc0e6ee0e99b165974244e749f40f33d465f56447bae8ce3

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
  - ree
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
