- :class    : Sodium::Auth
  :family   : crypto_auth
  :constants: [ VERSION, BYTES, KEYBYTES ]
  
  :functions: 
    ! ''   : [ pointer, pointer, ulong_long, pointer, int ]
    :verify: [ pointer, pointer, ulong_long, pointer, int ]

  :implementations:
    - &default_auth
      :name          : :HMACSHA512256
      :primitive     : :hmacsha512256
      :implementation: :ref
      :constants     : [ -, 32, 32 ]

    - :name          : :HMACSHA256
      :primitive     : :hmacsha256
      :implementation: ref
      :constants     : [ -, 32, 32 ]

  :default: *default_auth

- :class    : Sodium::Box
  :family   : crypto_box
  :constants:
    - VERSION
    - PUBLICKEYBYTES
    - SECRETKEYBYTES
    - BEFORENMBYTES
    - NONCEBYTES
    - ZEROBYTES
    - BOXZEROBYTES
    - MACBYTES
    
  :functions:
    ! ''         : [ pointer, pointer, ulong_long, pointer, pointer, pointer, int ]
    :open        : [ pointer, pointer, ulong_long, pointer, pointer, pointer, int ]
    :keypair     : [ pointer, pointer, int ]
    :beforenm    : [ pointer, pointer, pointer, int ]
    :afternm     : [ pointer, pointer, ulong_long, pointer, pointer, int ]
    :open_afternm: [ pointer, pointer, ulong_long, pointer, pointer, int ]

  :implementations:
    - &default_box
      :name          : :Curve25519XSalsa20Poly1305
      :primitive     : :curve25519xsalsa20poly1305
      :implementation: ref
      :constants     : [ -, 32, 32, 32, 24, 32, 16, 16 ]
        
  :default: *default_box