- :class    : Sodium::Auth
  :family   : crypto_auth
  :constants:
    - BYTES
    - KEYBYTES
  
  :functions: 
    ~      : [ pointer, pointer, ulong_long, pointer, int ]
    :verify: [ pointer, pointer, ulong_long, pointer, int ]

  :primitives:
    - :HMACSHA512256
    - :HMACSHA256

- :class    : Sodium::Box
  :family   : crypto_box
  :constants:
    - PUBLICKEYBYTES
    - SECRETKEYBYTES
    - BEFORENMBYTES
    - NONCEBYTES
    - ZEROBYTES
    - BOXZEROBYTES
    - MACBYTES
    
  :functions:
    ~            : [ pointer, pointer, ulong_long, pointer, pointer, pointer, int ]
    :open        : [ pointer, pointer, ulong_long, pointer, pointer, pointer, int ]
    :keypair     : [ pointer, pointer, int ]
    :beforenm    : [ pointer, pointer, pointer, int ]
    :afternm     : [ pointer, pointer, ulong_long, pointer, pointer, int ]
    :open_afternm: [ pointer, pointer, ulong_long, pointer, pointer, int ]

  :primitives:
    - :Curve25519XSalsa20Poly1305

- :class    : Sodium::Hash
  :family   : crypto_hash
  :constants:
    - BYTES

  :functions:
    ~: [ pointer, pointer, ulong_long, int ]

  :primitives:
    - :SHA512
    - :SHA256

- :class    : Sodium::OneTimeAuth
  :family   : crypto_onetimeauth
  :constants: 
    - BYTES
    - KEYBYTES

  :functions:
    ~      : [ pointer, pointer, ulong_long, pointer, int ]
    :verify: [ pointer, pointer, ulong_long, pointer, int ]

  :primitives:
    - :Poly1305

- :class    : Sodium::SecretBox
  :family   : crypto_secretbox
  :constants:
    - KEYBYTES
    - NONCEBYTES
    - ZEROBYTES
    - BOXZEROBYTES

  :functions:
    ~    : [ pointer, pointer, ulong_long, pointer, pointer, int ]
    :open: [ pointer, pointer, ulong_long, pointer, pointer, int ]

  :primitives:
    - :XSalsa20Poly1305

- :class    : Sodium::Sign
  :family   : crypto_sign
  :constants:
    - BYTES
    - PUBLICKEYBYTES
    - SECRETKEYBYTES

  :functions:
    ~      : [ pointer, pointer, pointer, ulong_long, pointer, int ]
    open   : [ pointer, pointer, pointer, ulong_long, pointer, int ]
    keypair: [ pointer, pointer, int ]

  :primitives:
    - :Ed25519